### ISSUE TITLE
More gentle error on not existing tag

### ISSUE THREAD

**Issue by szpak** [mattbrictson/chandler#34]
Currently Chandler fails with:

```
/home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/changelog.rb:38:in `fetch': undefined method `version_number' for nil:NilClass (NoMethodError)
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/commands/push.rb:60:in `changelog_version_and_notes_for_tag'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/commands/push.rb:43:in `block in each_tag_with_version_and_notes'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/commands/push.rb:42:in `each'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/commands/push.rb:42:in `each_tag_with_version_and_notes'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/commands/push.rb:29:in `call'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/lib/chandler/cli.rb:22:in `run'
	from /home/foo/.gem/ruby/gems/chandler-0.7.0/exe/chandler:4:in `<top (required)>'
	from /home/foo/bin/chandler:22:in `load'
	from /home/foo/bin/chandler:22:in `<main>'
(...)
```
in the station a requested single tag is not found. There could be nicer dedicated error message for that.

**Comment by mattbrictson** [comment]
Yes, agreed. I have no immediate plans for when I'll work on a next release of Chandler, but better error handling will surely be at the top of the feature list.

**Comment by mattbrictson** [comment]
⚠️ **This project is no longer actively maintained.** I have found myself embracing tools like [release-drafter](https://github.com/apps/release-drafter) to keep release notes updated automatically, rather than relying on a manually edited CHANGELOG.md. If you are interested in taking over chandler development, let me know by [opening an issue](https://github.com/mattbrictson/chandler/issues/new).
